data:
  train_files: /home/share/wenhao/datasets/hiyouga_math12k/train-00000-of-00001.parquet
  val_files: /home/share/wenhao/datasets/hiyouga_math12k/test-00000-of-00001.parquet
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 1024
  max_response_length: 6800  # over 6000: OOM
  rollout_batch_size: 256  # divisible by number of GPUs, also divisible by
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 128 # 144  # 128, global batch size must be divisible by micro_batch_size_per_device_for_update ** 2
    micro_batch_size_per_device_for_update: 4  # 4
    micro_batch_size_per_device_for_experience: 16 # 12  # 16
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 1.0e-3
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /data/wenhao/long_short_lora/models
      # /data/sunyi/hf_cache/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-1.5B/snapshots/530ca3e1ad39d440e182c2e4317aa40f012512fa
      # /data/wenhao/long_short_lora/models
      # /data/sunyi/hf_cache/hub/models--deepseek-ai--DeepSeek-R1-Distill-Qwen-7B/snapshots/6602cadec947dbb53e64f3d8d6425320b2197247/
      enable_gradient_checkpointing: true
      trust_remote_code: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    temperature: 1.0
    n: 5
    gpu_memory_utilization: 0.35  # 0.3 if out of memory
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2 ##
    limit_images: 0

  ref:
    offload:
      offload_params: true

  reward:
    reward_type: function
    compute_score: math

trainer:
  total_episodes: 15
  logger: ["console", "wandb"]
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math
  n_gpus_per_node: 4 ##
  nnodes: 1
  val_freq: 9999999 ## 
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 1
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: /data/wuxinrui/easyr1_checkpoints
  load_checkpoint_path: null
  # save_checkpoint_path: /data/wenhao/easyr1/long_short_ft_ds_qwen_7b_0316
  # load_checkpoint_path: /data/wenhao/easyr1/long_short_ft_ds_qwen_7b_0316/global_step_60
